[feat] init setting
Team-Smeme/Smeme-android pull request #5
Opened 2022-12-27 08:48 UTC by taeheeL

## 요약
gradle, permission, color 세팅, actionBar 조정
### AS-IS

### TO-BE

## 반영일정

2022-12-27 09:39 UTC, waterminn commented
프로젝트는 추가한 다음 status까지 설정해주면 될 것 같습니다! 고생하셨습니다👍

2022-12-27 09:40 UTC, waterminn approved these changes
프로젝트는 추가한 다음 status까지 설정해주면 될 것 같습니다! 고생하셨습니다👍

2022-12-27 16:25 UTC, daehwan2yo requested changes
세팅 구성 감사합니다~!
리뷰 반영 후에 재 리뷰요청 부탁드리겠습니다~

2022-12-27 16:25 UTC, daehwan2yo commented on app/build.gradle
> +        sourceCompatibility JavaVersion.VERSION_11
java version 다들 default 로 어떤 version 쓰고 있을까요? 확인 한번 부탁드릴게요
https://mainia.tistory.com/6482

- jdk 8
- jdk 11
@waterminn @taeheeL

2022-12-27 16:25 UTC, daehwan2yo commented on app/build.gradle
> +        sourceCompatibility JavaVersion.VERSION_11
+공부하면 좋을것
- 8 과 11 의 차이는 무엇일까요
- kotlin 이랑 무슨 상관일까요

2022-12-27 16:25 UTC, daehwan2yo commented on app/build.gradle
> +    // kotlinx-serialization-json
우리가 당장 쓰지 않을 의존들도 여럿 보이는 것 같은데,
필요할때마다 추가해서 사용하는 건 어떨까요?
- 불필요한 의존 빌드
- 이후 버저닝 관리 포인트 증가

2022-12-27 16:25 UTC, daehwan2yo commented on app/src/main/java/com/sopt/smeme/util/EnqueueUtil.kt
> +fun <T> Call<T>.enqueueUtil(
해당 부분은 프로젝트 전반 layer 에서 사용되어지는 util 코드라기보다는 network 를 다루는 layer 와 관련된 부분이라 생각되어 현재는 제거하고 이후 network 관련 베이스 구성할때 추가하면 좋을것같은데 어떻게 생각하실까요

2022-12-27 16:25 UTC, daehwan2yo commented on app/src/main/java/com/sopt/smeme/util/SnackUtil.kt
> +fun showSnackBar(view: View, msg: String) {
Snack 도 위와 마찬가지 입니다. 
View 와 관련된 layer 에서 다루면 좋을것같습니다

2022-12-27 16:25 UTC, daehwan2yo commented on app/src/main/java/com/sopt/smeme/util/extension/LifeCycleExtension.kt
> +inline fun LifecycleOwner.repeatOnStarted(crossinline block: suspend () -> Unit) {
해당 함수에 대해서 아직 제가 이해가 부족해서 추가적인 설명이 가능할까요?

- 객체의 생명주기 관리를 자동화하기 위함인지?
- 명시적으로 생명주기를 관리하기 위한 로직일지?

2022-12-27 16:25 UTC, daehwan2yo commented on app/src/main/java/com/sopt/smeme/util/extension/SafeLetExtension.kt
> +inline fun <T1 : Any, T2 : Any, R : Any> safeLet(p1: T1?, p2: T2?, block: (T1, T2) -> R?): R? {
`safeLet` 네이밍은 무슨 의미일까요??

2022-12-28 07:26 UTC, taeheeL commented on app/build.gradle
> +        sourceCompatibility JavaVersion.VERSION_11
저는 17로 되어있네요

2022-12-28 07:26 UTC, taeheeL commented on app/build.gradle
> +    // kotlinx-serialization-json
리뷰 반영해서 조절하겠습니다

2022-12-28 07:28 UTC, taeheeL commented on app/src/main/java/com/sopt/smeme/util/EnqueueUtil.kt
> +fun <T> Call<T>.enqueueUtil(
그럼 초기에는 제거하고 나중에 불러올 수 있게끔 처리 해두겠습니다!

2022-12-28 07:29 UTC, taeheeL commented on app/src/main/java/com/sopt/smeme/util/SnackUtil.kt
> +fun showSnackBar(view: View, msg: String) {
옙

2022-12-28 07:41 UTC, taeheeL commented on app/src/main/java/com/sopt/smeme/util/extension/LifeCycleExtension.kt
> +inline fun LifecycleOwner.repeatOnStarted(crossinline block: suspend () -> Unit) {
음 간단히 말씀드리자면 생명주기에 맞춰 코루틴은 안전하게 사용하게끔 해주는 함수입니다!

2022-12-28 07:43 UTC, taeheeL commented on app/src/main/java/com/sopt/smeme/util/extension/SafeLetExtension.kt
> +inline fun <T1 : Any, T2 : Any, R : Any> safeLet(p1: T1?, p2: T2?, block: (T1, T2) -> R?): R? {
안전하게 지정한다..?

2022-12-28 08:43 UTC, waterminn commented on app/build.gradle
> +        sourceCompatibility JavaVersion.VERSION_11
저도 17 입니다! 안스에서는 11 쓰고 있고요

2022-12-28 14:48 UTC, daehwan2yo commented on app/src/main/java/com/sopt/smeme/translate/TempTranslateActivity.kt
> +class TempTranslateActivity : AppCompatActivity() {
해당 부분은 브랜치 새롭게 파서 반영 부탁드리겠습니다~
init 의 목적에서 벗어난 커밋인것같습니다~

2022-12-28 14:49 UTC, daehwan2yo commented on app/src/main/java/com/sopt/smeme/translate/TempTranslateActivity.kt
> +class TempTranslateActivity : AppCompatActivity() {
관련 부분 우선 제거 반영 해두겠습니다

2022-12-28 15:27 UTC, daehwan2yo approved these changes

2022-12-28 15:28 UTC, daehwan2yo commented
merge 부탁드리겠습니다~

2022-12-30 04:12 UTC, merged